### ISSUE TITLE
[BUG] STDIN different behavior on Linux vs. Mac OS X

### ISSUE THREAD

**Issue by sjsrey** [ttscoff/doing#136] opened 2022-03-08 19:23 UTC
**Describe the bug**

STDIN on Linux results in a @done tag to the most recent entry. On Mac, a new entry is created.

**To Reproduce**

On Mac OSX:

```
echo "debugging on mac os x" | doing done
```
results in a new entry:
```
-  2022-03-08 11:03 | debugging on mac os x @done(2022-03-08 11:03)
````

On Linux:
```
echo "debugging on mac Linux" | doing done
```
results in a tag @done on the most recent entry:

```
- 2022-03-08 10:52 | @infra debugging doing commit log on linux @done(2022-03-08 10:55)

```

**Expected behavior**

A new entry on Linux, rather than a @done tag on the most recent entry.

**Desktop (please complete the following information):**

### Mac
 - Platform: Mac
 - OS: Monterrey
 - Version: 12.2.1

**Doing version**

 - Result of `doing -v`: 2.1.36

**Ruby version**

 - Result of `ruby -v`:  2.6.8p205

### Linux

- Platform: Linux
- OS: Debian
- Version: 11 (bullseye)

**Doing version**

 - Result of `doing -v`: 2.1.36

**Ruby version**

 - Result of `ruby -v`:  2.7.4p191

**Additional context**

I stumbled on this in trying to setup [git logging](https://brettterpstra.com/2014/03/20/logging-git-commits-with-doing/). On the Mac side this works as expected, but on the Linux side the git commits only result in the @done tag being added to the most recent entry in the doing file. I see that the hook is getting fired as the `doing_backup` files are getting added on the Linux side. 

My hunch is there is some difference in the way STDIN is being handled on the two OS?

**Comment by ttscoff** [comment] 2022-03-08 21:24
Yeah, I ran into a bit of this in testing. STDIN.stat.size returns 0 on Linux systems even when there's piped input. Tried to work around it but couldn't find a good way to check STDIN that was cross-platform. I'll look into it again next time I'm hacking on Doing.

**Comment by sjsrey** [comment] 2022-03-08 22:54
When that time comes, [this](http://footle.org/2008/08/21/checking-for-stdin-inruby/) may work (at least it seems to work for both linux and mac for me).

Thanks for the work on `doing` - it is a great tool!

**Comment by ttscoff** [comment] 2022-03-09 00:34
Oh awesome, that's exactly what I've been looking for.

- Brett

**Comment by ttscoff** [comment] 2022-03-12 17:41
Pushed the fix, will release a new gem shortly. Once I do, please test and confirm the issue is resolved for you. Thanks for the pointer on this one. 

Unsure how this will play on Windows systems these days. WSL should function the same as the Linux systems you're testing on, I think?

**Comment by ttscoff** [comment] 2022-03-12 17:57
Version 2.1.37 has been pushed to the gem server, `gem install doing` should update to it now.

**Comment by ttscoff** [comment] 2022-03-12 17:59
Reopening this issue until I get confirmation of the fix.

**Comment by sjsrey** [comment] 2022-03-12 23:26
Updating to 2.1.38 and the bug is fixed. 
Thanks!

**Comment by ttscoff** [comment] 2022-03-13 00:35
👍

**Closed by ttscoff** 2022-03-13 00:35 UTC
