### ISSUE TITLE
[BUG] `doing today` and `doing show all --from "today"` return different results at some times of the day

### ISSUE THREAD

**Issue by ecsongradi-lifemoves** [ttscoff/doing#154] opened 2022-08-01 15:58 UTC
**Describe the bug**

The `doing show all --from "today"` and `doing today` commands return different results when run before a certain time of day in the pacific daylight timezone. I haven't been able to nail down the exact time but it seems to be around 11:00 AM pacific when the commands start to return the same results. `doing today` seems to show all entries from the day while `doing show all --from "today"` only shows entries up to a certain point.

**To Reproduce**

Run both commands with a number of entries for the current day in the AM in pacific timezone. The below commands were run within a minute of one another at around 8:48 AM pacific time.

Debug results for `doing show all --from "today"`:

```
╰─$ GLI_DEBUG=true DOING_DEBUG=true doing show all --from "today"
       7:51am ║ Messaging and work tracking @a/wadmin @done(2022-08-01 08:11)                    [Currently ] 00:20
>      Config: Local config files found:
>      Editor: Using /usr/local/bin/nvim from config 'editors.default' for default
>      Editor: Using /usr/local/bin/nvim from config 'editors.config' for config
>      Editor: Using /usr/local/bin/nvim from config 'editors.doing_file' for doing_file
>      Parser: date/time string "today" interpreted as 2022-08-01 00:00:00 -0700
>      Parser: date/time string "today" interpreted as 2022-08-01 08:00:00 -0700
>      Parser: date range interpreted as 2022-08-01 00:00 -- 2022-08-01 08:00
>        Read: read file /Users/ericc/Documents/notes/doing/doing_log.taskpaper
>      Output: 1 item shown
>       Pager: Using less -FXr
```

Debug results for `doing today`:

```
╰─$ GLI_DEBUG=true DOING_DEBUG=true doing today
       7:51am ║ Messaging and work tracking @a/wadmin @done(2022-08-01 08:11)                    [Currently ] 00:20
       8:28am ║ Winter 23 sandbox preview instructions @a/analyze @p/voyager                     [Currently ] 00:08
              ║ @done(2022-08-01 08:36)
       8:37am ║ Messaging and work tracking @a/wadmin @done(2022-08-01 08:42)                    [Currently ] 00:05
>      Config: Local config files found:
>      Editor: Using /usr/local/bin/nvim from config 'editors.default' for default
>      Editor: Using /usr/local/bin/nvim from config 'editors.config' for config
>      Editor: Using /usr/local/bin/nvim from config 'editors.doing_file' for doing_file
>        Read: read file /Users/ericc/Documents/notes/doing/doing_log.taskpaper
>      Output: 3 items shown
>       Pager: Using less -FXr
```

**Expected behavior**

I would expect both commands to return the same set of entries.

**Desktop (please complete the following information):**

 - Platform: Mac
 - OS: Catalina
 - Version 10.15.7

**Doing version**

`doing version 2.1.64`

**Ruby version**

`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]`

**Comment by ttscoff** [comment] 2023-08-29 22:10
Still trying to track this down. As of 5:10PM CST, both commands have identical results. Will try again tomorrow around 11am and see if I can spot a difference.

**Comment by ttscoff** [comment] 2024-03-26 15:50
The chronify function was returning 10am if no end date was specified with `--from` (which would typically be a range but was intended to work with `--from today` or `--from 3/12/23`). This should be fixed in the next update.

**Closed by ttscoff** 2024-03-26 15:50 UTC
